/* To avoid CSS expressions while still supporting IE 7 and IE 6, use this script */
/* The script tag referencing this file must be placed before the ending body tag. */

/* Use conditional comments in order to target IE 7 and older:
<!--[if lt IE 8]><!-->
<script src="ie7/ie7.js"></script>
<!--<![endif]-->
*/

(function () {
    function addIcon(el, entity) {
        var html = el.innerHTML;
        el.innerHTML = '<span style="font-family: \'anychart\'">' + entity + '</span>' + html;
    }

    var icons = {
            'ac-enlarge': '&#xe9f8;',
            'ac-small-caps': '&#xe9f9;',
            'ac-overline': '&#xe9fb;',
            'ac-resize': '&#xe9fc;',
            'ac-zoom-in': '&#xe9fd;',
            'ac-anc-c': '&#xe9f3;',
            'ac-anc-lc': '&#xe9f1;',
            'ac-anc-rc': '&#xe9f2;',
            'ac-anc-lb': '&#xe9ea;',
            'ac-anc-lt': '&#xe9ec;',
            'ac-anc-rt': '&#xe9ef;',
            'ac-anc-rb': '&#xe9f0;',
            'ac-anc-cb': '&#xe900;',
            'ac-anc-ct': '&#xe9eb;',
            'ac-logo': '&#xe901;',
            'ac-anychart': '&#xe902;',
            'ac-anychart2': '&#xe903;',
            'ac-desktop': '&#xe904;',
            'ac-chart-column': '&#xe905;',
            'ac-chart-gauge': '&#xe906;',
            'ac-folder': '&#xe907;',
            'ac-file-image-o': '&#xe908;',
            'ac-map-o': '&#xe909;',
            'ac-book': '&#xe90a;',
            'ac-envelope': '&#xe90b;',
            'ac-phone-call': '&#xe90c;',
            'ac-support': '&#xe90d;',
            'ac-print': '&#xe90e;',
            'ac-print2': '&#xe90f;',
            'ac-position-center2': '&#xe910;',
            'ac-rectangle-2': '&#xe911;',
            'ac-upload': '&#xe912;',
            'ac-cloud-upload': '&#xe913;',
            'ac-download-zip': '&#xe914;',
            'ac-jsfiddle': '&#xe915;',
            'ac-line': '&#xe916;',
            'ac-horizontal-line': '&#xe917;',
            'ac-vertical-line': '&#xe918;',
            'ac-infinite-line': '&#xe919;',
            'ac-ray': '&#xe91a;',
            'ac-rectangle': '&#xe91b;',
            'ac-ellipse': '&#xe91c;',
            'ac-triangle': '&#xe91d;',
            'ac-fibonacci-arc': '&#xe91e;',
            'ac-fibonacci-fan': '&#xe91f;',
            'ac-fibonacci-retracement': '&#xe920;',
            'ac-fibonacci-timezones': '&#xe921;',
            'ac-andrews-pitchfork': '&#xe922;',
            'ac-trend-channel': '&#xe923;',
            'ac-question-circle-thin': '&#xe924;',
            'ac-ruler-paint-brush-o': '&#xe925;',
            'ac-plus': '&#xe926;',
            'ac-minus': '&#xe927;',
            'ac-check-circle-thick': '&#xe928;',
            'ac-chevron-circle-left-thin': '&#xe929;',
            'ac-chevron-circle-right-thin': '&#xe92a;',
            'ac-chevron-circle-up-thin': '&#xe92b;',
            'ac-chevron-circle-down-thin': '&#xe92c;',
            'ac-linkedin': '&#xe92d;',
            'ac-anystock': '&#xe92e;',
            'ac-anygantt': '&#xe92f;',
            'ac-anymap': '&#xe930;',
            'ac-anymap2': '&#xe931;',
            'ac-api': '&#xe932;',
            'ac-javascript': '&#xe933;',
            'ac-globe': '&#xe934;',
            'ac-charts-many': '&#xe935;',
            'ac-bars': '&#xe936;',
            'ac-search': '&#xe937;',
            'ac-star-4': '&#xe938;',
            'ac-triangle-right': '&#xe939;',
            'ac-position-left': '&#xe93a;',
            'ac-position-right': '&#xe93b;',
            'ac-question-circle': '&#xe93c;',
            'ac-question-circle-o': '&#xe93d;',
            'ac-plane': '&#xe93e;',
            'ac-smile': '&#xe93f;',
            'ac-disk-slash': '&#xe940;',
            'ac-v-line-dotted': '&#xe941;',
            'ac-check': '&#xe942;',
            'ac-remove': '&#xe943;',
            'ac-check-thin': '&#xe944;',
            'ac-fill': '&#xe945;',
            'ac-remove2-thin': '&#xe946;',
            'ac-check-circle-o': '&#xe947;',
            'ac-remove-circle': '&#xe948;',
            'ac-chevron-circle-left': '&#xe949;',
            'ac-chevron-circle-right': '&#xe94a;',
            'ac-chevron-circle-up': '&#xe94b;',
            'ac-chevron-circle-down': '&#xe94c;',
            'ac-bookmark': '&#xe94d;',
            'ac-mobile-phone': '&#xe94e;',
            'ac-chevron-up': '&#xe94f;',
            'ac-chevron-down': '&#xe950;',
            'ac-download-picture': '&#xe951;',
            'ac-download-chart': '&#xe952;',
            'ac-chevron-up-thick': '&#xe953;',
            'ac-chevron-down-thick': '&#xe954;',
            'ac-tint': '&#xe955;',
            'ac-position-top': '&#xe956;',
            'ac-arrow-up': '&#xe957;',
            'ac-arrow-down': '&#xe958;',
            'ac-arrow-up-left-square': '&#xe959;',
            'ac-position-bottom': '&#xe95a;',
            'ac-arrow-up-right-square': '&#xe95b;',
            'ac-arrow-right-square': '&#xe95c;',
            'ac-arrow-down-right-square': '&#xe95d;',
            'ac-remove-thin': '&#xe95e;',
            'ac-arrow-down-left-square': '&#xe95f;',
            'ac-arrow-left-square': '&#xe960;',
            'ac-chevron-left': '&#xe961;',
            'ac-chevron-right': '&#xe962;',
            'ac-chevron-left-thick': '&#xe963;',
            'ac-arrow-right-thin': '&#xe964;',
            'ac-chevron-right-thick': '&#xe965;',
            'ac-arrow-left': '&#xe966;',
            'ac-arrow-right': '&#xe967;',
            'ac-arrow-left-thin': '&#xe968;',
            'ac-arrow-up-square': '&#xe969;',
            'ac-arrow-down-square': '&#xe96a;',
            'ac-arrow-up-left-thin': '&#xe96b;',
            'ac-arrow-up-thin': '&#xe96c;',
            'ac-share': '&#xe96d;',
            'ac-arrow-up-right-thin': '&#xe96e;',
            'ac-pause': '&#xe96f;',
            'ac-stop': '&#xe970;',
            'ac-arrow-down-right-thin': '&#xe971;',
            'ac-arrow-down-thin': '&#xe972;',
            'ac-arrow-down-left-thin': '&#xe973;',
            'ac-undo': '&#xe974;',
            'ac-redo': '&#xe975;',
            'ac-forward2': '&#xe976;',
            'ac-map2-o': '&#xe977;',
            'ac-reply': '&#xe978;',
            'ac-play': '&#xe979;',
            'ac-search2': '&#xe97a;',
            'ac-backward': '&#xe97b;',
            'ac-forward': '&#xe97c;',
            'ac-facebook': '&#xe97d;',
            'ac-underline': '&#xe97e;',
            'ac-twitter': '&#xe97f;',
            'ac-code': '&#xe980;',
            'ac-sort': '&#xe981;',
            'ac-sort-asc': '&#xe982;',
            'ac-sort-desc': '&#xe983;',
            'ac-html5': '&#xe984;',
            'ac-font': '&#xe985;',
            'ac-bold': '&#xe986;',
            'ac-italic': '&#xe987;',
            'ac-strikethrough': '&#xe988;',
            'ac-sort-alpha-asc': '&#xe989;',
            'ac-info': '&#xe98a;',
            'ac-sort-alpha-desc': '&#xe98b;',
            'ac-question': '&#xe98c;',
            'ac-sort-amount-asc': '&#xe98d;',
            'ac-sort-amount-desc': '&#xe98e;',
            'ac-chart-ruler': '&#xe98f;',
            'ac-chart-ruler-pencil': '&#xe990;',
            'ac-chart-ruler-pencil2': '&#xe991;',
            'ac-ruler-paint-brush': '&#xe992;',
            'ac-universal-access': '&#xe993;',
            'ac-low-vision': '&#xe994;',
            'ac-deaf': '&#xe995;',
            'ac-sort-numeric-asc': '&#xe996;',
            'ac-sort-numeric-desc': '&#xe997;',
            'ac-exclamation': '&#xe998;',
            'ac-keyboard-o': '&#xe999;',
            'ac-folder-open': '&#xe99a;',
            'ac-clone': '&#xe99b;',
            'ac-object-group': '&#xe99c;',
            'ac-object-ungroup': '&#xe99d;',
            'ac-chart-database-o': '&#xe99e;',
            'ac-chart-database-o2': '&#xe99f;',
            'ac-trash-o': '&#xe9a0;',
            'ac-calendar': '&#xe9a1;',
            'ac-calendar-plus-o': '&#xe9a2;',
            'ac-file-excel-o': '&#xe9a3;',
            'ac-triangle-left': '&#xe9a4;',
            'ac-file-pdf-o': '&#xe9a5;',
            'ac-star': '&#xe9a6;',
            'ac-star-half-o': '&#xe9a7;',
            'ac-star-o': '&#xe9a8;',
            'ac-file-archive-o': '&#xe9a9;',
            'ac-file-code-o': '&#xe9aa;',
            'ac-user-plus': '&#xe9ab;',
            'ac-caret-left': '&#xe9ac;',
            'ac-caret-right': '&#xe9ad;',
            'ac-caret-down': '&#xe9ae;',
            'ac-caret-up': '&#xe9af;',
            'ac-file-text': '&#xe9b0;',
            'ac-align-left': '&#xe9b1;',
            'ac-align-center': '&#xe9b2;',
            'ac-align-right': '&#xe9b3;',
            'ac-align-justify': '&#xe9b4;',
            'ac-random': '&#xe9b5;',
            'ac-dot-square-o': '&#xe9b6;',
            'ac-bullhorn': '&#xe9b7;',
            'ac-picture-o': '&#xe9b8;',
            'ac-chart-area': '&#xe9b9;',
            'ac-chart-financial': '&#xe9ba;',
            'ac-chart-column2': '&#xe9bb;',
            'ac-checkbox-checked': '&#xe9bc;',
            'ac-head-arrow': '&#xe9bd;',
            'ac-ellipse-thin': '&#xe9be;',
            'ac-cross': '&#xe9bf;',
            'ac-diagonal-cros': '&#xe9c0;',
            'ac-diamond': '&#xe9c1;',
            'ac-users': '&#xe9c2;',
            'ac-pentagon': '&#xe9c3;',
            'ac-square': '&#xe9c4;',
            'ac-star-1': '&#xe9c5;',
            'ac-star-2': '&#xe9c6;',
            'ac-star-3': '&#xe9c7;',
            'ac-user-tie': '&#xe9c8;',
            'ac-star-5': '&#xe9c9;',
            'ac-trapezium': '&#xe9ca;',
            'ac-triangle-down': '&#xe9cb;',
            'ac-clipboard': '&#xe9cc;',
            'ac-rectangle-1': '&#xe9cd;',
            'ac-triangle-up': '&#xe9ce;',
            'ac-h-line-thickness-1': '&#xe9cf;',
            'ac-h-line-thickness-2': '&#xe9d0;',
            'ac-h-line-thickness-3': '&#xe9d1;',
            'ac-h-line-thickness-4': '&#xe9d2;',
            'ac-h-line-thickness-5': '&#xe9d3;',
            'ac-h-line-dotted-1': '&#xe9d4;',
            'ac-h-line-dotted-2': '&#xe9d5;',
            'ac-h-line-dotted-3': '&#xe9d6;',
            'ac-h-line-dotted-4': '&#xe9d7;',
            'ac-h-line-dotted-5': '&#xe9d8;',
            'ac-h-line-dashed-1': '&#xe9d9;',
            'ac-h-line-dashed-2': '&#xe9da;',
            'ac-h-line-dashed-3': '&#xe9db;',
            'ac-h-line-dashed-4': '&#xe9dc;',
            'ac-h-line-dashed-5': '&#xe9dd;',
            'ac-puzzle-o': '&#xe9de;',
            'ac-fill-o': '&#xe9df;',
            'ac-free': '&#xe9e0;',
            'ac-chart-ruler-o': '&#xe9e1;',
            'ac-puzzle': '&#xe9e2;',
            'ac-download': '&#xe9e3;',
            'ac-git': '&#xe9e4;',
            'ac-cog-o': '&#xe9e5;',
            'ac-asterisk': '&#xe9e6;',
            'ac-unlock-alt': '&#xe9e7;',
            'ac-unlock': '&#xe9e8;',
            'ac-position-center': '&#xe9e9;',
            'ac-comment': '&#xe9ed;',
            'ac-refresh': '&#xe9ee;',
            'ac-cog': '&#xe9f4;',
            'ac-comment-o': '&#xe9f5;',
            'ac-comments-o': '&#xe9f6;',
            'ac-square-double-o': '&#xe9f7;',
            'ac-rss': '&#xe9fa;',
            'ac-question-circle-1': '&#xea09;',
            'ac-info-circle': '&#xea0c;',
            'ac-bullhorn-2': '&#xf0a1;',
            'ac-group': '&#xf0c0;',
            'ac-save': '&#xf0c7;',
            'ac-pinterest': '&#xf0d2;',
            'ac-light-bulb': '&#xf0eb;',
            'ac-reverse': '&#xf1da;',
            'ac-net': '&#xf1e0;',
            'ac-mouse-pointer': '&#xf245;',
            '0': 0
        },
        els = document.getElementsByTagName('*'),
        i, c, el;
    for (i = 0; ; i += 1) {
        el = els[i];
        if (!el) {
            break;
        }
        c = el.className;
        c = c.match(/icon-[^\s'"]+/);
        if (c && icons[c[0]]) {
            addIcon(el, icons[c[0]]);
        }
    }
}());
